# Generated by Django 5.1.2 on 2025-04-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Category"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("quantity", models.CharField(max_length=64, verbose_name="Name")),
                ("price", models.FloatField()),
                (
                    "bargain_price",
                    models.FloatField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="bargain price",
                    ),
                ),
                ("units", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="variants",
                    ),
                ),
            ],
        ),
    ]
