# Generated by Django 5.1.2 on 2025-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="units",
            field=models.IntegerField(default=0),
        ),
    ]
