# Generated by Django 5.1.2 on 2025-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_productvariant_tags_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="product",
            table="Product",
        ),
        migrations.AlterModelTable(
            name="productvariant",
            table="ProductVariant",
        ),
    ]
